name: Build Ceres DEB

on:
  workflow_call:

jobs:
  build-ceres:
    name: Build Ceres Solver DEB
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - name: Install required tools
        run: |
          apt-get update
          apt-get install -y git sudo

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y cmake make build-essential \
            libeigen3-dev libgflags-dev libgoogle-glog-dev \
            libatlas-base-dev libsuitesparse-dev \
            debhelper devscripts fakeroot wget

      - name: Build DEB package
        working-directory: projects/ceres-solver
        run: ./scripts/build_deb.sh

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v3
        with:
          name: ceres-solver-deb
          path: ../*.deb
