name: Build Ceres Solver DEB (Matrix)

on:
  workflow_call:

jobs:
  build-ceres:
    name: Build Ceres Solver deb for ${{ matrix.arch }} / Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.workspace }}
      PROJ_PATH: ${{ github.workspace }}/projects/ceres-solver
    strategy:
      matrix:
        arch: [amd64, arm64]
        ubuntu: [20.04, 22.04, 24.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Package in Docker
        run: |
          IMAGE=ubuntu:${{ matrix.ubuntu }}
          ARCH=${{ matrix.arch }}
          TAG=ceres-${ARCH}-ubuntu${{ matrix.ubuntu }}

          docker run --rm --platform=linux/${ARCH} \
            -v ${{ github.workspace }}:/workspace \
            $IMAGE \
            bash -c "apt update && \
                     apt install -y sudo git wget cmake make build-essential \
                     libeigen3-dev libgflags-dev libgoogle-glog-dev \
                     libatlas-base-dev libsuitesparse-dev fakeroot dpkg-dev && \
                     cd /workspace/projects/ceres-solver && \
                     ARCH=$ARCH UBUNTU_VER=${{ matrix.ubuntu }} PROJ_PATH=${{ env.PROJ_PATH }} ./scripts/build_deb.sh"

      - name: Rename .deb with matrix info
        run: |
          cd projects/ceres-solver
          DEB=$(ls *.deb)
          mv "$DEB" "ceres-solver_2.2.0_${{ matrix.arch }}_ubuntu${{ matrix.ubuntu }}.deb"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ceres-solver-${{ matrix.arch }}-ubuntu${{ matrix.ubuntu }}
          path: projects/ceres-solver/ceres-solver_2.2.0_${{ matrix.arch }}_ubuntu${{ matrix.ubuntu }}.deb
          if-no-files-found: error
          compression-level: 0
