name: Build Ceres DEB

on:
  workflow_call:

jobs:
  build-ceres:
    name: Build Ceres Solver DEB
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    outputs:
      artifact-path: ${{ steps.set-path.outputs.artifact-path }}
    steps:
      - name: Install required tools
        run: apt update && apt install -y git sudo

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y cmake make build-essential \
            libeigen3-dev libgflags-dev libgoogle-glog-dev \
            libatlas-base-dev libsuitesparse-dev \
            debhelper devscripts fakeroot wget

      - name: Build DEB package
        working-directory: projects/ceres-solver
        run: ./scripts/build_deb.sh

      - name: Set output path
        id: set-path
        run: echo "artifact-path=$(realpath projects/ceres-solver/../*.deb)" >> "$GITHUB_OUTPUT"

  upload:
    name: Upload DEB from host
    runs-on: ubuntu-latest
    needs: build-ceres
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload DEB
        uses: actions/upload-artifact@v3
        with:
          name: ceres-solver-deb
          path: projects/ceres-solver/../*.deb
